### ISSUE TITLE
x-proxy无法使用

### ISSUE THREAD

**Issue by QwertyEK** [Kayuii/hpool-miner#5]
x-proxy无法运行 日志如下

<div class="x-grid3-row x-grid3-row-first x-grid3-row-selected" id="ext-gen28315" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: dotted dotted solid; border-color: rgb(172, 172, 172) rgb(172, 172, 172) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-image: none; background-color: rgb(230, 245, 255) !important; color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
server: | stdout
-- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | host: 0.0.0.0 | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | port: 9190 | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | log: | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | level: "info" | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | out: "./log/proxy.log"run : x-proxy | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | 2021-06-16T11:48:19.175+0800	INFO	engine/engine.go:402	=====&gt; initialize database connections | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | panic: unable to open database file: no such file or directory | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | &nbsp; | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | goroutine 1 [running]: | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | github.com/GoAdminGroup/go-admin/modules/db.(*Sqlite).InitDB.func1() | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | vendor/github.com/GoAdminGroup/go-admin/modules/db/sqlite.go:98 +0x2a5 | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | sync.(*Once).doSlow(0xc00038d4c8, 0xc00053b228) | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | /usr/local/go/src/sync/once.go:68 +0xec | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | sync.(*Once).Do(...) | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | /usr/local/go/src/sync/once.go:59 | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | github.com/GoAdminGroup/go-admin/modules/db.(*Sqlite).InitDB(0xc00038d4c0, 0xc0000fd530, 0xc00053b2e0, 0x0) | stdout
-- | -- | --

</div><div class="x-grid3-row " style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | vendor/github.com/GoAdminGroup/go-admin/modules/db/sqlite.go:84 +0x9a | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | github.com/GoAdminGroup/go-admin/engine.(*Engine).initDatabase(0xc0004a48c0, 0xc0004a48c0) | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | vendor/github.com/GoAdminGroup/go-admin/engine/engine.go:181 +0x1af | stdout
-- | -- | --

</div><div class="x-grid3-row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | github.com/GoAdminGroup/go-admin/engine.(*Engine).AddConfig(0xc0004a48c0, 0xc0000fd1a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1625c5a, 0x5, ...) | stdout
-- | -- | --

</div><div class="x-grid3-row" role="row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | vendor/github.com/GoAdminGroup/go-admin/engine/engine.go:141 +0x93 | stdout
-- | -- | --

</div><div class="x-grid3-row" role="row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | main.startServer() | stdout
-- | -- | --

</div><div class="x-grid3-row" role="row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | main.go:94 +0x958 | stdout
-- | -- | --

</div><div class="x-grid3-row" role="row" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(255, 255, 255) rgb(237, 237, 237) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background-color: rgb(255, 255, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | main.main() | stdout
-- | -- | --

</div><div class="x-grid3-row x-grid3-row-last x-grid3-row-over" role="row" id="ext-gen28297" style="margin: 0px; padding: 0px; border-width: 0px 0px 1px; border-style: solid; border-color: rgb(220, 230, 240) rgb(220, 230, 240) rgb(235, 240, 245); border-image: initial; cursor: default; width: 983px; background: none left top repeat-x rgb(245, 250, 255); color: rgb(80, 90, 100); font-size: 12px; font-family: verdana, arial, tahoma, helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; height: 24px;">
03:48:19 | main.go:42 +0x25
-- | --

</div>

**Comment by Kayuii** [comment]
I've fixed it
